[workspace]
members = [
    "packages/*",
    "contracts/fungible-tokens/*",
    "contracts/non-fungible-tokens/*",
    "contracts/ecosystem/*",
    "contracts/data-storage/*",
    "contracts/app/*",
    "contracts/finance/*",
    # "contracts/automation/*",
    "contracts/modules/*",
    "contracts/os/*",

    #Internal
    "tests-integration",
]
resolver = "2"

[profile.release]
debug = false
debug-assertions = false
opt-level = 'z'
codegen-units = 1
rpath = false
lto = true
overflow-checks = true
panic = 'abort'
strip = true

[workspace.dependencies]
andromeda-std = { path = "./packages/std" }
andromeda-macros = { path = "./packages/std/macros", version = "1.0.0-rc1" }
andromeda-non-fungible-tokens = { path = "./packages/andromeda-non-fungible-tokens" }
andromeda-fungible-tokens = { path = "./packages/andromeda-fungible-tokens" }
andromeda-finance = { path = "./packages/andromeda-finance" }
andromeda-data-storage = { path = "./packages/andromeda-data-storage" }
andromeda-modules = { path = "./packages/andromeda-modules" }
andromeda-app = { path = "./packages/andromeda-app" }
andromeda-ecosystem = { path = "./packages/andromeda-ecosystem" }
andromeda-testing = { path = "./packages/andromeda-testing" }


strum_macros = "0.24.3"
cosmwasm-std = "1.5.2"
cw-utils = "1.0.3"
cw-storage-plus = "1.2.0"
cw2 = "1.1.2"
cw20 = "1.1.2"
cw20-base = "1.1.2"
cw721 = "0.18.0"
cw721-base = { version = "0.18.0", features = ["library"] }
cw-asset = "3.0.0"
cosmwasm-schema = "1.5.2"
semver = "1.0.0"
enum-repr = "0.2.6"
cw-multi-test = "1.0.0"
serde = { version = "1.0.127" }
