[package]
name = "andromeda-std"
version = "1.0.0-rc1"
edition = "2021"
rust-version = "1.69.0"
description = "The standard library for creating an Andromeda Digital Object"
license = "MIT"

[features]
primitive = []
modules = ["andromeda-macros/modules"]
module_hooks = ["andromeda-macros/module_hooks"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3", "cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
semver = { workspace = true }
cw20 = { version = "1.0.1" }
cw20-base = { workspace = true, features = ["library"] }
cw721-base = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw-asset = { version = "3.0.0" }
thiserror = { version = "1.0.21" }
lazy_static = "1"
hex = "0.4"
regex = { version = "1.9.1", default-features = false }
andromeda-macros = { workspace = true }
strum_macros = { workspace = true }
cw721 = { workspace = true }
serde-json-wasm = "0.5.0"
enum-repr = { workspace = true }

[dev-dependencies]
cw-multi-test = { version = "1.0.0" }
