[package]
name = "andromeda-macros"
version = "1.0.0-rc1"
edition = "2021"
rust-version = "1.69.0"
description = "Macros for Andromeda Digital Objects"
license = "MIT"

[lib]
proc-macro = true

[features]
modules = []
module_hooks = []

[dependencies]
syn = { version = "1.0.0", features = ["derive"] }
proc-macro2 = "1.0"
quote = "1.0"
